basePath: /
definitions:
  main.Product:
    properties:
      description:
        type: string
      id:
        type: string
      price:
        type: number
      title:
        type: string
    type: object
info:
  contact: {}
  description: Product service API
  title: AWS Shop Backend API
  version: "1.0"
paths:
  /products:
    get:
      consumes:
      - application/json
      description: Returns a list of all available products
      operationId: get-products-list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Product'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get list of all products
      tags:
      - Products
  /products/{id}:
    get:
      consumes:
      - application/json
      description: Returns a single product by its ID
      operationId: get-product-by-id
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Product'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get a product by ID
      tags:
      - Products
swagger: "2.0"
